#!/bin/sh
rm -rf ./build/*.mk
rm -rf ./build/gyp-mac-tool
rm -rf ./build/libraries
rm -rf ./build/Makefile
rm -rf ./build/ninja
rm -rf ./build/xcode
rm -rf ./build/DerivedSources/
rm -rf ./build/Release/
rm -rf ./build/Debug/
rm -rf ./build/openssl.build
rm -rf ./build/http_parser.build
rm -rf ./build/libffi.build
rm -rf ./build/uv.build
rm -rf ./build/v8.build
rm -rf ./build/tint.build
rm -rf ./build/cares.build
rm -rf ./build/uv.build
rm -rf ./build/zlib.build