[Constructor (optional TCPServerOptions options)]
interface TCPServerSocket : EventTarget {
    readonly    attribute DOMString      localAddress;
    readonly    attribute unsigned short localPort;
    readonly    attribute boolean        addressReuse;
    readonly    attribute ReadyState     readyState;
                attribute EventHandler   onopen;
                attribute EventHandler   onconnect;
                attribute EventHandler   onerror;
                attribute EventHandler   onconnecterror;
    void close ();
    void suspend ();
    void resume ();
};
